service: fhr-sqs-update-all-games

frameworkVersion: '3'

configValidationMode: error

provider:
  name: aws
  runtime: nodejs20.x
  stage: v1
  region: ${env:FHR_REGION}
  stackName: ${env:FHR_ENV}

resources:
  Resources:
    MyQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: FHR-UpdateAllGames-${env:FHR_ENV}
